#!/bin/sh

PROJECT="earthissuetracker"

cd /opt/virtualenvs
sudo rm -rf spirithunter
sudo virtualenv --python=$(which python2.7) ${PROJECT}
sudo chown -R vagrant:vagrant ${PROJECT}
. ${PROJECT}/bin/activate
pip install Django Markdown pysqlite
